// src/app/layout.js
export const metadata = {
  title: "AI Multi-Agent System",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
